# -*- coding: utf-8 -*-
"""
Created on Sun Feb 11 01:30:31 2024

@author: AbuOsama
"""

import pandas as pd
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pio.templates.default = "plotly_white"
import matplotlib.pyplot as plt
%matplotlib inline

data = pd.read_csv("supply_chain_data.csv")
df = pd.DataFrame(data)
print(data.head())
print(df.columns)    # Header of the dataset

# Descriptive Statistics of the dataset
print(data.describe())

# Analyzing the Supply Chain by looking at the relationship between the price
# of the products and the revenue generated by them:

fig = px.scatter(data, x='Price', 
                 y='Revenue generated', 
                 color='Product type', 
                 hover_data=['Number of products sold'], 
                 trendline="ols")
fig.show()    

sales_data = data.groupby('Product type')['Number of products sold'].sum().reset_index()

pie_chart = px.pie(sales_data, values='Number of products sold', names='Product type', 
                   title='Sales by Product Type', 
                   hover_data=['Number of products sold'],
                   hole=0.5,
                   color_discrete_sequence=px.colors.qualitative.Pastel)
                   
pie_chart.update_traces(textposition='inside', textinfo='percent+label')
pie_chart.show()

